CREATE TABLE [dbo].[User]
(
	[UserId] NUMERIC IDENTITY NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[FirstName] NVARCHAR(255) NOT NULL,
	[LastName] NVARCHAR(255) NOT NULL,
	[Role] INT NOT NULL DEFAULT 1,

	CONSTRAINT [PK_User] PRIMARY KEY ([UserId])
)
