name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - master
    paths:
      - app/**
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        
      - name: ls
        run: ls dist

      - name: Upload to Azure Blob Storage
        uses: Azure/CLI@v1
        with:
          azcliversion: 2.50.0
          inlineScript: |
            az storage blob upload-batch -d \$web -s dist --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --debug --output json
